name: Redis compability testing
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  redis-comp:
    strategy:
      fail-fast: false
      matrix:
        include:
          - redis-version: 6.2-rc1
            test-target: ct
          - redis-version: 6.0.9
            test-target: ct
          - redis-version: 5.0.10
            test-target: ct-tcp
          - redis-version: 4.0.14
            test-target: ct-tcp
          - redis-version: 3.2.7
            test-target: ct-tcp
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Hex packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-hex-

      - name: Install Erlang/OTP
        run: |
          DEB_NAME="esl-erlang_23.1-1~ubuntu~focal_amd64.deb"
          curl -f https://packages.erlang-solutions.com/erlang/debian/pool/$DEB_NAME -o $DEB_NAME
          sudo dpkg --install $DEB_NAME

      - name: Install faketime
        run: |
          sudo apt update
          sudo apt install -yy --no-install-recommends faketime

      - name: Build
        run: make compile

      - name: Test
        run: |
          REDIS_VERSION=${{ matrix.redis-version }} make ${{ matrix.test-target }}
